version: '3.4'

services:
    nodejs:
        container_name: techradar-nodejs
        image: node:18.8-alpine3.16
        user: ${HOST_UID:-1000}:${HOST_GID:-1001}
        ports:
            - "8020:8020"
        volumes:
            - .:/app:rw
        working_dir: /app
        environment:
            NPM_CONFIG_LOGLEVEL: info
            NODE_ENV: ${APP_ENV:-dev}
        command: yarn dev --host 0.0.0.0 --port 8020
