import { entry } from './types';

const entries: entry[] = [
    {
        quadrantId: 3,
        ringId: 'adopt',
        label: 'AWS EMR',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'adopt',
        label: 'Spark',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'trial',
        label: 'Airflow',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'trial',
        label: 'AWS Data Pipeline',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'trial',
        label: 'Flink',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'trial',
        label: 'Google BigQuery',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'trial',
        label: 'Presto',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'assess',
        label: 'Hadoop',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'assess',
        label: 'YARN',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'hold',
        label: 'Esper',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'adopt',
        label: 'AWS S3',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'adopt',
        label: 'Cassandra',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'adopt',
        label: 'Elasticsearch',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'adopt',
        label: 'etcd',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'adopt',
        label: 'PostgreSQL',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'adopt',
        label: 'Redis',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'adopt',
        label: 'Solr',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'trial',
        label: 'AWS DynamoDB',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'trial',
        label: 'HDFS',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'assess',
        label: 'Consul',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'assess',
        label: 'Google Bigtable',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'assess',
        label: 'RocksDB',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'hold',
        label: 'Aerospike',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'hold',
        label: 'CouchBase',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'hold',
        label: 'HBase',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'hold',
        label: 'Memcached',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'hold',
        label: 'MongoDB',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'hold',
        label: 'MySQL',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'hold',
        label: 'Oracle DB',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'hold',
        label: 'ZooKeeper',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 2,
        ringId: 'adopt',
        label: 'Akka (Scala)',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 2,
        ringId: 'adopt',
        label: 'Node.js',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 2,
        ringId: 'adopt',
        label: 'Play (Scala)',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 2,
        ringId: 'adopt',
        label: 'ReactJS',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 2,
        ringId: 'adopt',
        label: 'RxJava (Android)',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 2,
        ringId: 'adopt',
        label: 'scikit-learn',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 2,
        ringId: 'adopt',
        label: 'Spring',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 2,
        ringId: 'trial',
        label: 'Akka-Http',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 2,
        ringId: 'trial',
        label: 'Angular',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 2,
        ringId: 'trial',
        label: 'AspectJ',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 2,
        ringId: 'trial',
        label: 'Camel',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 2,
        ringId: 'trial',
        label: 'Camunda',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 2,
        ringId: 'trial',
        label: 'OpenNLP',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 2,
        ringId: 'trial',
        label: 'TensorFlow',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 2,
        ringId: 'trial',
        label: 'Thymeleaf',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 2,
        ringId: 'assess',
        label: 'Aurelia',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 2,
        ringId: 'assess',
        label: 'Ember.js',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 2,
        ringId: 'assess',
        label: 'gRPC',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 2,
        ringId: 'assess',
        label: 'Http4s',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 2,
        ringId: 'assess',
        label: 'jOOQ',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 2,
        ringId: 'assess',
        label: 'Redux',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 2,
        ringId: 'assess',
        label: 'Vert.x',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 2,
        ringId: 'assess',
        label: 'Vue.js',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 2,
        ringId: 'hold',
        label: 'Activiti',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 2,
        ringId: 'hold',
        label: 'AngularJS 1.x',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 2,
        ringId: 'hold',
        label: 'BackboneJS',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 2,
        ringId: 'hold',
        label: 'Drools',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 2,
        ringId: 'hold',
        label: 'Spray',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 1,
        ringId: 'adopt',
        label: 'Docker',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 1,
        ringId: 'adopt',
        label: 'Hystrix',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 1,
        ringId: 'adopt',
        label: 'Kubernetes',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 1,
        ringId: 'adopt',
        label: 'Nginx',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 1,
        ringId: 'adopt',
        label: 'OpenTracing',
        active: true,
        moved: 1,
    },
    {
        quadrantId: 1,
        ringId: 'adopt',
        label: 'Tomcat',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 1,
        ringId: 'adopt',
        label: 'ZMON',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 1,
        ringId: 'trial',
        label: 'Failsafe',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 1,
        ringId: 'trial',
        label: 'Undertow',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 1,
        ringId: 'assess',
        label: 'AWS Lambda',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 1,
        ringId: 'hold',
        label: 'STUPS',
        active: true,
        moved: -1,
    },
    {
        quadrantId: 0,
        ringId: 'adopt',
        label: 'Go',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 0,
        ringId: 'adopt',
        label: 'Java',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 0,
        ringId: 'adopt',
        label: 'JavaScript',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 0,
        ringId: 'adopt',
        label: 'OpenAPI (Swagger)',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 0,
        ringId: 'adopt',
        label: 'Python',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 0,
        ringId: 'adopt',
        label: 'Scala',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 0,
        ringId: 'adopt',
        label: 'Swift',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 0,
        ringId: 'hold',
        label: 'Clojure',
        active: true,
        moved: -1,
    },
    {
        quadrantId: 0,
        ringId: 'trial',
        label: 'GraphQL',
        active: true,
        moved: 1,
    },
    {
        quadrantId: 0,
        ringId: 'hold',
        label: 'Haskell',
        active: true,
        moved: -1,
    },
    {
        quadrantId: 0,
        ringId: 'trial',
        label: 'Kotlin',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 0,
        ringId: 'trial',
        label: 'TypeScript',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 0,
        ringId: 'assess',
        label: 'R',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 0,
        ringId: 'hold',
        label: 'Rust',
        active: true,
        moved: -1,
    },
    {
        quadrantId: 3,
        ringId: 'adopt',
        label: 'AWS SNS',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'adopt',
        label: 'AWS SQS',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'adopt',
        label: 'Kafka',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'adopt',
        label: 'Nakadi',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'trial',
        label: 'RabbitMQ',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'assess',
        label: 'AWS Kinesis',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'hold',
        label: 'ActiveMQ',
        active: true,
        moved: 0,
    },
    {
        quadrantId: 3,
        ringId: 'hold',
        label: 'HornetQ',
        active: true,
        moved: 0,
    },
];

export default entries;
